/* This file was generated by qmake with the info from <root>/src/qftp/qftp.pro. */
#ifndef QT_QTFTP_VERSION_H
#define QT_QTFTP_VERSION_H
#define QTFTP_VERSION_STR "5.0.0"
#define QTFTP_VERSION 0x050000
#endif // QT_QTFTP_VERSION_H
